
server:
  port: 8041
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:log4jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO

# App Properties(spring-boot-jwt-market-kurly-secret-key-spring-boot-jwt-market-kurly-secret-key)
jwt:
  key: spring-boot-jwt-market-kurly-secret-key-spring-boot-jwt-market-kurly-secret-key